### PR TITLE
Switch from components to using SVG images

### PR DESCRIPTION
**Pull request by nathanstitt**
AKA what @philschatz suggested we do from the beginning 

Otherwise when React renders the HTML before and after the placeholder component, sometimes it's not valid HTML, leading to invariant errors.

No visible UI changes, but here's a screenshot 
screen shot 2016-07-01 at 4 04 17 pm

### CODE REVIEW

**Comment by philschatz** [comment]
yay, thanks! 

_nitpick:_ 💭  I wonder if the image paths in general could be a little less hardcoded.

**Comment by nathanstitt** [comment]
Yes, the image path could be a var, but not a global one.  The issue is that `less` needs to find the assets for a `url` call in a relative location from the source file.  So if I were to set a var `images-path` to `'../../../images`, it would work, but only for files that are at the same nesting level.

I went ahead and set a scoped var with it though - it'll still save us one duplication .

**Comment by philschatz** [comment]
ah, _me_ wonders if all icons should be defined in 1 directory (I thought we were already doing something similar, maybe each icon was a mixin or something) and then just include them in the files where they are used, no?

**Comment by nathanstitt** [comment]
No, I don't think we can do that.  Like I said, the `url()` reference needs to be relative from the file that's calling it.  I looked through `tutor-js` and that seems like how we're calling everything there as well.  Maybe I'm missing it though?

**Comment by philschatz** [comment]
I guess I was suggesting having 1 file that defines all the icons used in 1 place (maybe move https://github.com/openstax/react-components/blob/192769c70a152f193a6e825ef5e08a7f346c5461/resources/styles/components/breadcrumbs/icons.less up a directory)

**Comment by nathanstitt** [comment]
Ah!  I see, sorry I was slow - I thought you were suggesting variable interpolation.  Made the change

**Pull request merged**
