### PR TITLE
add "Report Trouble" link

### PR DESCRIPTION
**Pull request by nathanstitt**
To be used on CC and Tutor to link to display exercise UID and link to trouble reporting form.

### CODE REVIEW

**Comment by philschatz** [comment]
Oh my, that's a lot of hard-coded UUID's... Is there no better way?

**Comment by nathanstitt** [comment]
yeah, I agree :)  

The book prop is a convenience to pre-fill  book select radio button on the form.  

I don't see any other way since the strings it needs to target are set on the form.  If the form input's value's were set to the book uuid then we just send the UUID along to the form, but then the responses spreadsheet would have plain UUID values that would be hard to understand.

However!  the book property is not being used right by any of the other components since they all lack a course (and/or book) to pass on.  I thought ConceptCoach had that info available, but it looks like it does not.  Maybe we should just remove it altogether?

**Comment by philschatz** [comment]
Yep, just noticed (on `dev`) that the book radio is never filled. I think we can deploy without prefilling in the book. thoughts @openstax/test ?

**Comment by nathanstitt** [comment]
I think ideally we should make a BE form that we could have complete control over.  I'm not sure if that should live on Tutor though, probably part of exercises would make the most sense.

**Pull request merged**
