### PR TITLE
Updating React Components Dependencies

### PR DESCRIPTION
**Pull request by jivewise**
This updates the react components dependencies for this ticket: https://www.pivotaltracker.com/story/show/113875411

### CODE REVIEW

**Comment by jivewise** [comment]
I think i still need to check a few screenshots here and there

**Comment by nathanstitt** [comment]
Looks good to me.  Does anyone else on @openstax/tutor-fe have an opinion?  Otherwise I'll merge this afternoon

**Comment by philschatz** [comment]
I think conclusion was to upgrade `tutor-js` first since upgrading tutor will be the bulk of work in upgrading React.

**Comment by philschatz** [comment]
This has merge conflicts; can you rebase `master` in to here?

**Comment by jivewise** [comment]
I'm going to close this in favor of https://github.com/openstax/react-components/pull/60

**Pull request closed without merging**
