### PR TITLE
clean up the exercise uid display for exercises

### PR DESCRIPTION
**Pull request by pandafulmanda**
Also, amending tests with lots more details, esp to test around #36
## After

screen shot 2016-01-11 at 12 50 08 pm
## Before

screen shot 2016-01-11 at 12 50 26 pm

### CODE REVIEW

**Comment by nathanstitt** [comment]
TESTSSSSSS (yay!)

Not sure if I like the exercise id pushed down beside the answer button or not... I guess it doesn't really matter though

**Comment by philschatz** [comment]
@nathanstitt The 1st screen is _After_ and the 2nd one is _Before_ so I think others also objected at the placement of the id

**Comment by pandafulmanda** [comment]
im unsure too, but the positions now are definitely awkward

**Comment by nathanstitt** [comment]
@philschatz Yeah I totally missed that.  Yes the after is much better than the before :)

**Pull request merged**
